#if !canImport(ObjectiveC)
import XCTest

extension MeasureTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MeasureTests = [
        ("testStringFormat", testStringFormat),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MeasureTests.__allTests__MeasureTests),
    ]
}
#endif
