#if !canImport(ObjectiveC)
import XCTest

extension TestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TestTests = [
        ("testLifetime", testLifetime),
        ("testThrows", testThrows),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TestTests.__allTests__TestTests),
    ]
}
#endif
